# Generated by Django 2.2.1 on 2019-05-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='login',
            new_name='username',
        ),
    ]
