# Generated by Django 2.2.1 on 2019-05-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190519_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('email',)},
        ),
    ]
