# Generated by Django 2.2.1 on 2019-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190519_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='token',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
